export interface City {
  name: string
  postalCode: string
}

export interface Province {
  name: string
  cities: City[]
}

export const PROVINCES: Province[] = [
  {
    name: "Buenos Aires",
    cities: [
      { name: "La Plata", postalCode: "1900" },
      { name: "Mar del Plata", postalCode: "7600" },
      { name: "Bahía Blanca", postalCode: "8000" },
      { name: "Luján", postalCode: "6700" },
      { name: "Merlo", postalCode: "1722" },
      { name: "Moreno", postalCode: "1744" },
      { name: "Morón", postalCode: "1708" },
      { name: "Lanús", postalCode: "1824" },
      { name: "Quilmes", postalCode: "1878" },
      { name: "Avellaneda", postalCode: "1870" },
      { name: "San Isidro", postalCode: "1642" },
      { name: "Vicente López", postalCode: "1638" },
      { name: "Tigre", postalCode: "1648" },
      { name: "Pilar", postalCode: "1629" },
      { name: "Campana", postalCode: "2804" },
      { name: "Zárate", postalCode: "2800" },
      { name: "Chivilcoy", postalCode: "6620" },
      { name: "Pergamino", postalCode: "2700" },
      { name: "Junín", postalCode: "6000" },
      { name: "Tandil", postalCode: "7000" },
      { name: "Necochea", postalCode: "7630" },
      { name: "Olavarría", postalCode: "7400" },
      { name: "San Nicolás", postalCode: "2900" },
      { name: "La Matanza", postalCode: "1754" },
      { name: "Almirante Brown", postalCode: "1846" },
      { name: "Berazategui", postalCode: "1884" },
      { name: "Florencio Varela", postalCode: "1888" },
      { name: "Ezeiza", postalCode: "1804" },
      { name: "Escobar", postalCode: "1625" },
      { name: "San Fernando", postalCode: "1646" },
      { name: "General Rodríguez", postalCode: "1748" },
      { name: "Chascomús", postalCode: "7130" },
      { name: "Dolores", postalCode: "7100" },
      { name: "Azul", postalCode: "7300" },
      { name: "9 de Julio", postalCode: "6500" },
      { name: "Pehuajó", postalCode: "6450" },
      { name: "Trenque Lauquen", postalCode: "6400" },
      { name: "Lincoln", postalCode: "6070" },
      { name: "Bragado", postalCode: "6640" },
      { name: "25 de Mayo", postalCode: "6660" },
      { name: "Lobos", postalCode: "7240" },
      { name: "Cañuelas", postalCode: "1814" },
      { name: "San Vicente", postalCode: "1865" },
      { name: "Brandsen", postalCode: "1980" },
      { name: "Magdalena", postalCode: "1913" },
    ],
  },
  {
    name: "CABA",
    cities: [
      { name: "Palermo", postalCode: "1425" },
      { name: "Belgrano", postalCode: "1430" },
      { name: "Recoleta", postalCode: "1425" },
      { name: "Puerto Madero", postalCode: "1107" },
      { name: "Caballito", postalCode: "1405" },
      { name: "Flores", postalCode: "1406" },
      { name: "Floresta", postalCode: "1407" },
      { name: "Villa Urquiza", postalCode: "1431" },
      { name: "Devoto", postalCode: "1417" },
      { name: "Almagro", postalCode: "1414" },
      { name: "Balvanera", postalCode: "1213" },
      { name: "Once", postalCode: "1214" },
      { name: "San Telmo", postalCode: "1066" },
      { name: "La Boca", postalCode: "1151" },
      { name: "Barracas", postalCode: "1264" },
      { name: "Nuñez", postalCode: "1429" },
      { name: "Saavedra", postalCode: "1428" },
      { name: "Villa Crespo", postalCode: "1416" },
      { name: "Villa Luro", postalCode: "1440" },
      { name: "Mataderos", postalCode: "1440" },
      { name: "Liniers", postalCode: "1440" },
      { name: "Villa Soldati", postalCode: "1440" },
      { name: "Villa Riachuelo", postalCode: "1439" },
      { name: "Parque Patricios", postalCode: "1437" },
      { name: "Boedo", postalCode: "1221" },
      { name: "Constitución", postalCode: "1269" },
      { name: "Monserrat", postalCode: "1082" },
      { name: "San Nicolás", postalCode: "1012" },
      { name: "Retiro", postalCode: "1002" },
      { name: "Villa del Parque", postalCode: "1417" },
    ],
  },
  {
    name: "Catamarca",
    cities: [
      { name: "San Fernando del Valle de Catamarca", postalCode: "4700" },
      { name: "Andalgalá", postalCode: "4740" },
      { name: "Belén", postalCode: "4750" },
      { name: "Santa María", postalCode: "4139" },
      { name: "Tinogasta", postalCode: "5340" },
      { name: "Recreo", postalCode: "5260" },
      { name: "San José", postalCode: "4705" },
      { name: "Fiambalá", postalCode: "5345" },
    ],
  },
  {
    name: "Chaco",
    cities: [
      { name: "Resistencia", postalCode: "3500" },
      { name: "Presidencia Roque Sáenz Peña", postalCode: "3700" },
      { name: "Villa Ángela", postalCode: "3540" },
      { name: "Charata", postalCode: "3730" },
      { name: "Las Breñas", postalCode: "3722" },
      { name: "Castelli", postalCode: "3705" },
      { name: "Puerto Tirol", postalCode: "3505" },
      { name: "Fontana", postalCode: "3514" },
      { name: "Barranqueras", postalCode: "3503" },
      { name: "General José de San Martín", postalCode: "3701" },
    ],
  },
  {
    name: "Chubut",
    cities: [
      { name: "Rawson", postalCode: "9103" },
      { name: "Comodoro Rivadavia", postalCode: "9000" },
      { name: "Puerto Madryn", postalCode: "9120" },
      { name: "Trelew", postalCode: "9100" },
      { name: "Esquel", postalCode: "9200" },
      { name: "Gaiman", postalCode: "9105" },
      { name: "Sarmiento", postalCode: "9020" },
      { name: "Rada Tilly", postalCode: "9001" },
      { name: "Dolavon", postalCode: "9107" },
      { name: "Camarones", postalCode: "9111" },
    ],
  },
  {
    name: "Córdoba",
    cities: [
      { name: "Córdoba", postalCode: "5000" },
      { name: "Río Cuarto", postalCode: "5800" },
      { name: "Villa María", postalCode: "5900" },
      { name: "San Francisco", postalCode: "2400" },
      { name: "Carlos Paz", postalCode: "5152" },
      { name: "Alta Gracia", postalCode: "5186" },
      { name: "Bell Ville", postalCode: "2550" },
      { name: "Jesús María", postalCode: "5220" },
      { name: "Cruz del Eje", postalCode: "5280" },
      { name: "Villa Carlos Paz", postalCode: "5152" },
      { name: "Río Tercero", postalCode: "5850" },
      { name: "La Falda", postalCode: "5172" },
      { name: "Cosquín", postalCode: "5166" },
      { name: "Mina Clavero", postalCode: "5889" },
      { name: "Arroyito", postalCode: "2434" },
      { name: "Marcos Juárez", postalCode: "2580" },
      { name: "Laboulaye", postalCode: "6120" },
      { name: "Justiniano Posse", postalCode: "2553" },
      { name: "Villa Allende", postalCode: "5105" },
      { name: "Unquillo", postalCode: "5109" },
    ],
  },
  {
    name: "Corrientes",
    cities: [
      { name: "Corrientes", postalCode: "3400" },
      { name: "Goya", postalCode: "3450" },
      { name: "Paso de los Libres", postalCode: "3230" },
      { name: "Mercedes", postalCode: "3470" },
      { name: "Curuzú Cuatiá", postalCode: "3460" },
      { name: "Santo Tomé", postalCode: "3340" },
      { name: "Bella Vista", postalCode: "3432" },
      { name: "Saladas", postalCode: "3420" },
      { name: "Esquina", postalCode: "3196" },
      { name: "Monte Caseros", postalCode: "3220" },
    ],
  },
  {
    name: "Entre Ríos",
    cities: [
      { name: "Paraná", postalCode: "3100" },
      { name: "Concordia", postalCode: "3200" },
      { name: "Gualeguaychú", postalCode: "2820" },
      { name: "Concepción del Uruguay", postalCode: "3260" },
      { name: "Villaguay", postalCode: "3240" },
      { name: "Colón", postalCode: "3280" },
      { name: "Gualeguay", postalCode: "2840" },
      { name: "Victoria", postalCode: "3153" },
      { name: "Nogoyá", postalCode: "3150" },
      { name: "La Paz", postalCode: "3190" },
      { name: "Federación", postalCode: "3206" },
      { name: "Diamante", postalCode: "3105" },
    ],
  },
  {
    name: "Formosa",
    cities: [
      { name: "Formosa", postalCode: "3600" },
      { name: "Clorinda", postalCode: "3610" },
      { name: "Pirané", postalCode: "3606" },
      { name: "Las Lomitas", postalCode: "3630" },
      { name: "El Colorado", postalCode: "3603" },
      { name: "Ibarreta", postalCode: "3632" },
      { name: "Laguna Blanca", postalCode: "3613" },
    ],
  },
  {
    name: "Jujuy",
    cities: [
      { name: "San Salvador de Jujuy", postalCode: "4600" },
      { name: "Palpalá", postalCode: "4612" },
      { name: "La Quiaca", postalCode: "4650" },
      { name: "Libertador General San Martín", postalCode: "4512" },
      { name: "Humahuaca", postalCode: "4630" },
      { name: "Tilcara", postalCode: "4624" },
      { name: "Purmamarca", postalCode: "4618" },
      { name: "El Carmen", postalCode: "4603" },
      { name: "Perico", postalCode: "4608" },
    ],
  },
  {
    name: "La Pampa",
    cities: [
      { name: "Santa Rosa", postalCode: "6300" },
      { name: "General Pico", postalCode: "6360" },
      { name: "Toay", postalCode: "6301" },
      { name: "Eduardo Castex", postalCode: "6380" },
      { name: "Realicó", postalCode: "6365" },
      { name: "Catriló", postalCode: "6330" },
      { name: "Victorica", postalCode: "6319" },
      { name: "25 de Mayo", postalCode: "8200" },
      { name: "Macachín", postalCode: "6307" },
      { name: "General Acha", postalCode: "8208" },
    ],
  },
  {
    name: "La Rioja",
    cities: [
      { name: "La Rioja", postalCode: "5300" },
      { name: "Chilecito", postalCode: "5360" },
      { name: "Aimogasta", postalCode: "5310" },
      { name: "Chepes", postalCode: "5470" },
      { name: "Villa Unión", postalCode: "5350" },
      { name: "Olta", postalCode: "5380" },
      { name: "Anillaco", postalCode: "5341" },
    ],
  },
  {
    name: "Mendoza",
    cities: [
      { name: "Mendoza", postalCode: "5500" },
      { name: "Godoy Cruz", postalCode: "5501" },
      { name: "Las Heras", postalCode: "5539" },
      { name: "Guaymallén", postalCode: "5519" },
      { name: "Maipú", postalCode: "5515" },
      { name: "San Rafael", postalCode: "5600" },
      { name: "Luján de Cuyo", postalCode: "5505" },
      { name: "Tunuyán", postalCode: "5560" },
      { name: "Malargüe", postalCode: "5613" },
      { name: "Rivadavia", postalCode: "5570" },
      { name: "San Martín", postalCode: "5579" },
      { name: "General Alvear", postalCode: "5620" },
      { name: "La Paz", postalCode: "5590" },
      { name: "Tupungato", postalCode: "5561" },
    ],
  },
  {
    name: "Misiones",
    cities: [
      { name: "Posadas", postalCode: "3300" },
      { name: "Oberá", postalCode: "3360" },
      { name: "Eldorado", postalCode: "3380" },
      { name: "Puerto Iguazú", postalCode: "3370" },
      { name: "Apóstoles", postalCode: "3350" },
      { name: "San Vicente", postalCode: "3328" },
      { name: "Leandro N. Alem", postalCode: "3315" },
      { name: "Jardín América", postalCode: "3328" },
      { name: "Montecarlo", postalCode: "3384" },
      { name: "San Pedro", postalCode: "3364" },
      { name: "Aristóbulo del Valle", postalCode: "3364" },
      { name: "Puerto Rico", postalCode: "3334" },
    ],
  },
  {
    name: "Neuquén",
    cities: [
      { name: "Neuquén", postalCode: "8300" },
      { name: "Cutral Co", postalCode: "8322" },
      { name: "Plottier", postalCode: "8316" },
      { name: "Cipolletti", postalCode: "8324" },
      { name: "San Martín de los Andes", postalCode: "8370" },
      { name: "Villa La Angostura", postalCode: "8407" },
      { name: "Zapala", postalCode: "8340" },
      { name: "Rincón de los Sauces", postalCode: "8319" },
      { name: "Centenario", postalCode: "8309" },
      { name: "Chos Malal", postalCode: "8353" },
    ],
  },
  {
    name: "Río Negro",
    cities: [
      { name: "Viedma", postalCode: "8500" },
      { name: "General Roca", postalCode: "8332" },
      { name: "San Carlos de Bariloche", postalCode: "8400" },
      { name: "Cipolletti", postalCode: "8324" },
      { name: "El Bolsón", postalCode: "8430" },
      { name: "Choele Choel", postalCode: "8360" },
      { name: "Sierra Grande", postalCode: "8532" },
      { name: "Río Colorado", postalCode: "8138" },
      { name: "Villa Regina", postalCode: "8336" },
      { name: "Allen", postalCode: "8328" },
      { name: "Catriel", postalCode: "8307" },
    ],
  },
  {
    name: "Salta",
    cities: [
      { name: "Salta", postalCode: "4400" },
      { name: "San Ramón de la Nueva Orán", postalCode: "4530" },
      { name: "Tartagal", postalCode: "4560" },
      { name: "Cafayate", postalCode: "4427" },
      { name: "Metán", postalCode: "4440" },
      { name: "Rosario de la Frontera", postalCode: "4190" },
      { name: "General Güemes", postalCode: "4430" },
      { name: "Embarcación", postalCode: "4550" },
      { name: "Joaquín V. González", postalCode: "4448" },
      { name: "San Antonio de los Cobres", postalCode: "4411" },
    ],
  },
  {
    name: "San Juan",
    cities: [
      { name: "San Juan", postalCode: "5400" },
      { name: "Rivadavia", postalCode: "5401" },
      { name: "Rawson", postalCode: "5411" },
      { name: "Caucete", postalCode: "5442" },
      { name: "San José de Jáchal", postalCode: "5460" },
      { name: "Villa Aberastain", postalCode: "5435" },
      { name: "Albardón", postalCode: "5419" },
      { name: "Pocito", postalCode: "5427" },
      { name: "Santa Lucía", postalCode: "5411" },
      { name: "Valle Fértil", postalCode: "5449" },
    ],
  },
  {
    name: "San Luis",
    cities: [
      { name: "San Luis", postalCode: "5700" },
      { name: "Villa Mercedes", postalCode: "5730" },
      { name: "Merlo", postalCode: "5881" },
      { name: "La Punta", postalCode: "5710" },
      { name: "Justo Daract", postalCode: "5738" },
      { name: "Buena Esperanza", postalCode: "5777" },
      { name: "Tilisarao", postalCode: "5770" },
      { name: "Concarán", postalCode: "5773" },
      { name: "Santa Rosa del Conlara", postalCode: "5779" },
    ],
  },
  {
    name: "Santa Cruz",
    cities: [
      { name: "Río Gallegos", postalCode: "9400" },
      { name: "Caleta Olivia", postalCode: "9011" },
      { name: "Pico Truncado", postalCode: "9017" },
      { name: "Las Heras", postalCode: "9017" },
      { name: "El Calafate", postalCode: "9405" },
      { name: "Puerto Deseado", postalCode: "9050" },
      { name: "Puerto San Julián", postalCode: "9310" },
      { name: "Perito Moreno", postalCode: "9040" },
      { name: "Río Turbio", postalCode: "9407" },
    ],
  },
  {
    name: "Santa Fe",
    cities: [
      { name: "Rosario", postalCode: "2000" },
      { name: "Santa Fe", postalCode: "3000" },
      { name: "Rafaela", postalCode: "2300" },
      { name: "Venado Tuerto", postalCode: "2600" },
      { name: "Casilda", postalCode: "2170" },
      { name: "Villa Gobernador Gálvez", postalCode: "2124" },
      { name: "Cañada de Gómez", postalCode: "2500" },
      { name: "San Lorenzo", postalCode: "2200" },
      { name: "Firmat", postalCode: "2609" },
      { name: "Reconquista", postalCode: "3560" },
      { name: "Esperanza", postalCode: "3080" },
      { name: "Santo Tomé", postalCode: "3016" },
      { name: "Granadero Baigorria", postalCode: "2152" },
      { name: "Roldán", postalCode: "2134" },
      { name: "Pérez", postalCode: "2121" },
      { name: "Arroyo Seco", postalCode: "2128" },
      { name: "El Trébol", postalCode: "2535" },
      { name: "Sunchales", postalCode: "2322" },
      { name: "Tostado", postalCode: "3060" },
      { name: "San Justo", postalCode: "3040" },
      { name: "Avellaneda", postalCode: "3561" },
      { name: "Malabrigo", postalCode: "3563" },
    ],
  },
  {
    name: "Santiago del Estero",
    cities: [
      { name: "Santiago del Estero", postalCode: "4200" },
      { name: "La Banda", postalCode: "4300" },
      { name: "Termas de Río Hondo", postalCode: "4220" },
      { name: "Añatuya", postalCode: "3760" },
      { name: "Frías", postalCode: "4230" },
      { name: "Monte Quemado", postalCode: "3745" },
      { name: "Quimilí", postalCode: "3740" },
      { name: "Loreto", postalCode: "4205" },
      { name: "Fernández", postalCode: "4326" },
    ],
  },
  {
    name: "Tierra del Fuego",
    cities: [
      { name: "Ushuaia", postalCode: "9410" },
      { name: "Río Grande", postalCode: "9420" },
      { name: "Tolhuin", postalCode: "9412" },
    ],
  },
  {
    name: "Tucumán",
    cities: [
      { name: "San Miguel de Tucumán", postalCode: "4000" },
      { name: "Tafí Viejo", postalCode: "4103" },
      { name: "Concepción", postalCode: "4146" },
      { name: "Aguilares", postalCode: "4152" },
      { name: "Yerba Buena", postalCode: "4107" },
      { name: "Monteros", postalCode: "4142" },
      { name: "Famaillá", postalCode: "4132" },
      { name: "Bella Vista", postalCode: "4162" },
      { name: "Lules", postalCode: "4128" },
      { name: "Tafí del Valle", postalCode: "4101" },
      { name: "Simoca", postalCode: "4172" },
    ],
  },
]
