import type { Product, GlobalParams, ScenarioConfig, User, Sale } from "@/types"

export const MOCK_USER: User = {
  uid: "admin-001",
  email: "admin@tiendaropa.com",
  name: "Admin",
  role: "admin",
}

export const DEFAULT_PARAMS: GlobalParams = {
  cart: {
    baseCharge: 0.15,
    paymentMethods: [
      { name: "Efectivo", rate: 0 },
      { name: "Tarjeta", rate: 0.03 },
      { name: "Transferencia", rate: 0.01 },
    ],
    bulkDiscounts: [
      { minQty: 3, discount: 0.05 },
      { minQty: 10, discount: 0.12 },
    ],
  },
  shipping: {
    fixedCost: 5000,
    freeShippingThreshold: 100000,
    freeShippingEnabled: true,
    announcementBannerEnabled: true,
    announcementBannerText: "Envío gratis en compras +$120.000 · 3 cuotas sin interés",
  },
  financial: {
    monthlyInflation: 3.5,
    generalTax: 21,
    usdExchangeRate: 1200,
  },
}

export const SCENARIOS: Record<string, ScenarioConfig> = {
  base: { label: "Base", inflationMultiplier: 1, salesMultiplier: 1 },
  optimistic: { label: "Optimista", inflationMultiplier: 0.7, salesMultiplier: 1.2 },
  pessimistic: { label: "Pesimista", inflationMultiplier: 1.5, salesMultiplier: 0.85 },
}

export const SIZES = ["XS", "S", "M", "L", "XL", "XXL"]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Remera Urban Fit",
    brand: "Urban Fit",
    category: "Remeras",
    gender: "unisex",
    price: 25000,
    previousPrice: 12000,
    description: "Remera de algodón moderno, corte unisex. Ideal para el día a día.",
    imageUrl: "https://placehold.co/600x800/7c5cfc/ffffff?text=Remera+UF",
    colors: [
      { name: "Negro", sizes: { XS: 4, S: 6, M: 8, L: 7, XL: 3, XXL: 1 } },
      { name: "Blanco", sizes: { XS: 3, S: 5, M: 7, L: 6, XL: 3, XXL: 1 } },
      { name: "Gris", sizes: { XS: 3, S: 4, M: 5, L: 5, XL: 2, XXL: 1 } },
    ],
    material: "Algodón 100%",
    tags: ["básico", "casual", "algodón"],
    seccion: "general",
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p2",
    name: "Campera EcoWear",
    brand: "EcoWear",
    category: "Camperas",
    gender: "unisex",
    price: 32000,
    previousPrice: 15000,
    description: "Campera sostenible con materiales reciclados. Corte moderno y cálido.",
    imageUrl: "https://placehold.co/600x800/ec4899/ffffff?text=Campera+EW",
    colors: [
      { name: "Verde Oliva", sizes: { XS: 2, S: 5, M: 9, L: 8, XL: 4, XXL: 2 } },
      { name: "Negro", sizes: { XS: 2, S: 4, M: 8, L: 7, XL: 3, XXL: 1 } },
      { name: "Beige", sizes: { XS: 1, S: 3, M: 8, L: 7, XL: 3, XXL: 1 } },
    ],
    material: "Poliéster reciclado",
    tags: ["sostenible", "eco", "abrigo"],
    seccion: "nueva-coleccion",
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p3",
    name: "Short SportPlus",
    brand: "SportPlus",
    category: "Shorts",
    gender: "hombre",
    price: 28000,
    previousPrice: 11000,
    description: "Short deportivo de alto rendimiento. Transpirable y liviano.",
    imageUrl: "https://placehold.co/600x800/10b981/ffffff?text=Short+SP",
    colors: [
      { name: "Azul", sizes: { XS: 3, S: 7, M: 10, L: 8, XL: 5, XXL: 2 } },
      { name: "Negro", sizes: { XS: 3, S: 7, M: 10, L: 9, XL: 5, XXL: 2 } },
      { name: "Rojo", sizes: { XS: 2, S: 6, M: 10, L: 8, XL: 5, XXL: 2 } },
    ],
    material: "Poliamida 85%, Elastano 15%",
    tags: ["deporte", "transpirable", "liviano"],
    seccion: "general",
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p4",
    name: "Pantalón Casual Club",
    brand: "Casual Club",
    category: "Pantalones",
    gender: "hombre",
    price: 22000,
    previousPrice: 10000,
    description: "Pantalón casual de corte recto. Cómodo y versátil para cualquier ocasión.",
    imageUrl: "https://placehold.co/600x800/f59e0b/ffffff?text=Pantalon+CC",
    colors: [
      { name: "Beige", sizes: { XS: 4, S: 6, M: 8, L: 7, XL: 5, XXL: 2 } },
      { name: "Negro", sizes: { XS: 4, S: 6, M: 7, L: 7, XL: 5, XXL: 3 } },
      { name: "Azul", sizes: { XS: 4, S: 6, M: 7, L: 6, XL: 4, XXL: 2 } },
    ],
    material: "Algodón 98%, Elastano 2%",
    tags: ["casual", "cómodo", "diario"],
    seccion: "general",
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p5",
    name: "Musculosa SportPlus",
    brand: "SportPlus",
    category: "Remeras",
    gender: "hombre",
    price: 18000,
    previousPrice: 8000,
    description: "Musculosa deportiva con tecnología anti-humedad.",
    imageUrl: "https://placehold.co/600x800/7c5cfc/ffffff?text=Musculosa+SP",
    colors: [
      { name: "Negro", sizes: { XS: 4, S: 7, M: 9, L: 7, XL: 5, XXL: 2 } },
      { name: "Blanco", sizes: { XS: 4, S: 6, M: 9, L: 7, XL: 5, XXL: 2 } },
      { name: "Gris", sizes: { XS: 4, S: 6, M: 9, L: 7, XL: 4, XXL: 2 } },
      { name: "Azul", sizes: { XS: 3, S: 6, M: 8, L: 7, XL: 4, XXL: 2 } },
    ],
    material: "Poliamida 90%, Elastano 10%",
    tags: ["deporte", "anti-humedad", "gimnasio"],
    seccion: "ofertas",
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p6",
    name: "Zapatillas SportPlus",
    brand: "SportPlus",
    category: "Accesorios",
    gender: "unisex",
    price: 55000,
    previousPrice: 25000,
    description: "Zapatillas de running con amortiguación avanzada.",
    imageUrl: "https://placehold.co/600x800/ec4899/ffffff?text=Zapatillas+SP",
    colors: [
      { name: "Blanco/Negro", sizes: { XS: 2, S: 4, M: 6, L: 5, XL: 3, XXL: 1 } },
      { name: "Azul", sizes: { XS: 2, S: 3, M: 5, L: 4, XL: 3, XXL: 1 } },
      { name: "Rojo", sizes: { XS: 1, S: 3, M: 4, L: 3, XL: 2, XXL: 1 } },
    ],
    material: "Sintético y malla",
    tags: ["calzado", "running", "deporte"],
    seccion: "nueva-coleccion",
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p7",
    name: "Sweater EcoWear",
    brand: "EcoWear",
    category: "Sweaters",
    gender: "unisex",
    price: 35000,
    previousPrice: 16000,
    description: "Sweater de lana reciclada. Suave, abrigado y sostenible.",
    imageUrl: "https://placehold.co/600x800/f59e0b/ffffff?text=Sweater+EW",
    colors: [
      { name: "Gris", sizes: { XS: 2, S: 5, M: 7, L: 6, XL: 4, XXL: 2 } },
      { name: "Verde", sizes: { XS: 3, S: 5, M: 7, L: 6, XL: 3, XXL: 2 } },
      { name: "Mostaza", sizes: { XS: 2, S: 4, M: 6, L: 6, XL: 3, XXL: 1 } },
    ],
    material: "Lana reciclada 80%, Algodón 20%",
    tags: ["sostenible", "abrigo", "invierno"],
    seccion: "general",
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p8",
    name: "Jean Recto 315",
    brand: "Casual Club",
    category: "Jeans",
    gender: "hombre",
    price: 45000,
    previousPrice: 20000,
    description: "Jean de corte recto con elástico. Cómodo y con estilo.",
    imageUrl: "https://placehold.co/600x800/10b981/ffffff?text=Jean+315",
    colors: [
      { name: "Azul Claro", sizes: { XS: 4, S: 6, M: 8, L: 7, XL: 4, XXL: 2 } },
      { name: "Azul Oscuro", sizes: { XS: 3, S: 5, M: 8, L: 7, XL: 4, XXL: 2 } },
      { name: "Negro", sizes: { XS: 3, S: 5, M: 8, L: 6, XL: 4, XXL: 1 } },
    ],
    material: "Algodón 97%, Elastano 3%",
    tags: ["jean", "clásico", "cómodo"],
    seccion: "ofertas",
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
]

export const MOCK_SALES: Sale[] = [
  { id: "s1", productId: "p1", productName: "Remera Urban Fit", brand: "Urban Fit", quantity: 50, unitPrice: 25000, date: "2026-01-15", size: "M" },
  { id: "s2", productId: "p1", productName: "Remera Urban Fit", brand: "Urban Fit", quantity: 30, unitPrice: 25000, date: "2026-02-10", size: "L" },
  { id: "s3", productId: "p2", productName: "Campera EcoWear", brand: "EcoWear", quantity: 20, unitPrice: 32000, date: "2026-01-20", size: "M" },
  { id: "s4", productId: "p2", productName: "Campera EcoWear", brand: "EcoWear", quantity: 15, unitPrice: 32000, date: "2026-03-05", size: "S" },
  { id: "s5", productId: "p3", productName: "Short SportPlus", brand: "SportPlus", quantity: 40, unitPrice: 28000, date: "2026-02-28", size: "L" },
  { id: "s6", productId: "p5", productName: "Musculosa SportPlus", brand: "SportPlus", quantity: 35, unitPrice: 18000, date: "2026-03-15", size: "M" },
  { id: "s7", productId: "p4", productName: "Pantalón Casual Club", brand: "Casual Club", quantity: 25, unitPrice: 22000, date: "2026-01-25", size: "L" },
  { id: "s8", productId: "p4", productName: "Pantalón Casual Club", brand: "Casual Club", quantity: 20, unitPrice: 22000, date: "2026-03-20", size: "M" },
  { id: "s9", productId: "p1", productName: "Remera Urban Fit", brand: "Urban Fit", quantity: 45, unitPrice: 25000, date: "2026-03-25", size: "S" },
  { id: "s10", productId: "p6", productName: "Zapatillas SportPlus", brand: "SportPlus", quantity: 10, unitPrice: 55000, date: "2026-02-05", size: "L" },
  { id: "s11", productId: "p7", productName: "Sweater EcoWear", brand: "EcoWear", quantity: 12, unitPrice: 35000, date: "2026-04-01", size: "M" },
  { id: "s12", productId: "p8", productName: "Jean Recto 315", brand: "Casual Club", quantity: 60, unitPrice: 45000, date: "2026-04-10", size: "XS" },
]

export const HOLIDAYS = [
  { date: "2026-01-01", name: "Año Nuevo" },
  { date: "2026-02-16", name: "Carnaval" },
  { date: "2026-03-24", name: "Día de la Memoria" },
  { date: "2026-05-01", name: "Día del Trabajador" },
  { date: "2026-05-25", name: "Revolución de Mayo" },
]
