import type { Product, GlobalParams, ScenarioConfig, User, Sale } from "@/types"

export const MOCK_USER: User = {
  uid: "admin-001",
  email: "admin@tiendaropa.com",
  role: "admin",
}

export const DEFAULT_PARAMS: GlobalParams = {
  cart: {
    baseCharge: 0.15,
    paymentMethods: [
      { name: "Efectivo", rate: 0 },
      { name: "Tarjeta", rate: 0.03 },
      { name: "Transferencia", rate: 0.01 },
    ],
    bulkDiscounts: [
      { minQty: 3, discount: 0.05 },
      { minQty: 10, discount: 0.12 },
    ],
  },
  shipping: {
    fixedCost: 5000,
    freeShippingThreshold: 100000,
    freeShippingEnabled: true,
  },
  financial: {
    monthlyInflation: 3.5,
    generalTax: 21,
    usdExchangeRate: 1200,
  },
}

export const SCENARIOS: Record<string, ScenarioConfig> = {
  base: { label: "Base", inflationMultiplier: 1, salesMultiplier: 1 },
  optimistic: { label: "Optimista", inflationMultiplier: 0.7, salesMultiplier: 1.2 },
  pessimistic: { label: "Pesimista", inflationMultiplier: 1.5, salesMultiplier: 0.85 },
}

export const SIZES = ["XS", "S", "M", "L", "XL", "XXL"]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Remera Urban Fit",
    brand: "Urban Fit",
    category: "Remeras",
    price: 25000,
    cost: 12000,
    description: "Remera de algodón moderno, corte unisex. Ideal para el día a día.",
    imageUrl: "https://placehold.co/600x800/7c5cfc/ffffff?text=Remera+UF",
    sizes: { XS: 10, S: 15, M: 20, L: 18, XL: 8, XXL: 3 },
    colors: ["Negro", "Blanco", "Gris"],
    material: "Algodón 100%",
    tags: ["básico", "casual", "algodón"],
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p2",
    name: "Campera EcoWear",
    brand: "EcoWear",
    category: "Camperas",
    price: 32000,
    cost: 15000,
    description: "Campera sostenible con materiales reciclados. Corte moderno y cálido.",
    imageUrl: "https://placehold.co/600x800/ec4899/ffffff?text=Campera+EW",
    sizes: { XS: 5, S: 12, M: 25, L: 22, XL: 10, XXL: 4 },
    colors: ["Verde Oliva", "Negro", "Beige"],
    material: "Poliéster reciclado",
    tags: ["sostenible", "eco", "abrigo"],
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p3",
    name: "Short SportPlus",
    brand: "SportPlus",
    category: "Shorts",
    price: 28000,
    cost: 11000,
    description: "Short deportivo de alto rendimiento. Transpirable y liviano.",
    imageUrl: "https://placehold.co/600x800/10b981/ffffff?text=Short+SP",
    sizes: { XS: 8, S: 20, M: 30, L: 25, XL: 15, XXL: 6 },
    colors: ["Azul", "Negro", "Rojo"],
    material: "Poliamida 85%, Elastano 15%",
    tags: ["deporte", "transpirable", "liviano"],
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p4",
    name: "Pantalón Casual Club",
    brand: "Casual Club",
    category: "Pantalones",
    price: 22000,
    cost: 10000,
    description: "Pantalón casual de corte recto. Cómodo y versátil para cualquier ocasión.",
    imageUrl: "https://placehold.co/600x800/f59e0b/ffffff?text=Pantalon+CC",
    sizes: { XS: 12, S: 18, M: 22, L: 20, XL: 14, XXL: 7 },
    colors: ["Beige", "Negro", "Azul"],
    material: "Algodón 98%, Elastano 2%",
    tags: ["casual", "cómodo", "diario"],
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p5",
    name: "Musculosa SportPlus",
    brand: "SportPlus",
    category: "Remeras",
    price: 18000,
    cost: 8000,
    description: "Musculosa deportiva con tecnología anti-humedad.",
    imageUrl: "https://placehold.co/600x800/7c5cfc/ffffff?text=Musculosa+SP",
    sizes: { XS: 15, S: 25, M: 35, L: 28, XL: 18, XXL: 8 },
    colors: ["Negro", "Blanco", "Gris", "Azul"],
    material: "Poliamida 90%, Elastano 10%",
    tags: ["deporte", "anti-humedad", "gimnasio"],
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p6",
    name: "Zapatillas SportPlus",
    brand: "SportPlus",
    category: "Accesorios",
    price: 55000,
    cost: 25000,
    description: "Zapatillas de running con amortiguación avanzada.",
    imageUrl: "https://placehold.co/600x800/ec4899/ffffff?text=Zapatillas+SP",
    sizes: { XS: 5, S: 10, M: 15, L: 12, XL: 8, XXL: 3 },
    colors: ["Blanco/Negro", "Azul", "Rojo"],
    material: "Sintético y malla",
    tags: ["calzado", "running", "deporte"],
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p7",
    name: "Sweater EcoWear",
    brand: "EcoWear",
    category: "Sweaters",
    price: 35000,
    cost: 16000,
    description: "Sweater de lana reciclada. Suave, abrigado y sostenible.",
    imageUrl: "https://placehold.co/600x800/f59e0b/ffffff?text=Sweater+EW",
    sizes: { XS: 7, S: 14, M: 20, L: 18, XL: 10, XXL: 5 },
    colors: ["Gris", "Verde", "Mostaza"],
    material: "Lana reciclada 80%, Algodón 20%",
    tags: ["sostenible", "abrigo", "invierno"],
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "p8",
    name: "Jean Recto 315",
    brand: "Casual Club",
    category: "Jeans",
    price: 45000,
    cost: 20000,
    description: "Jean de corte recto con elástico. Cómodo y con estilo.",
    imageUrl: "https://placehold.co/600x800/10b981/ffffff?text=Jean+315",
    sizes: { XS: 10, S: 16, M: 24, L: 20, XL: 12, XXL: 5 },
    colors: ["Azul Claro", "Azul Oscuro", "Negro"],
    material: "Algodón 97%, Elastano 3%",
    tags: ["jean", "clásico", "cómodo"],
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
]

export const MOCK_SALES: Sale[] = [
  { id: "s1", productId: "p1", productName: "Remera Urban Fit", brand: "Urban Fit", quantity: 50, unitPrice: 25000, cost: 12000, date: "2026-01-15", size: "M" },
  { id: "s2", productId: "p1", productName: "Remera Urban Fit", brand: "Urban Fit", quantity: 30, unitPrice: 25000, cost: 12000, date: "2026-02-10", size: "L" },
  { id: "s3", productId: "p2", productName: "Campera EcoWear", brand: "EcoWear", quantity: 20, unitPrice: 32000, cost: 15000, date: "2026-01-20", size: "M" },
  { id: "s4", productId: "p2", productName: "Campera EcoWear", brand: "EcoWear", quantity: 15, unitPrice: 32000, cost: 15000, date: "2026-03-05", size: "S" },
  { id: "s5", productId: "p3", productName: "Short SportPlus", brand: "SportPlus", quantity: 40, unitPrice: 28000, cost: 11000, date: "2026-02-28", size: "L" },
  { id: "s6", productId: "p5", productName: "Musculosa SportPlus", brand: "SportPlus", quantity: 35, unitPrice: 18000, cost: 8000, date: "2026-03-15", size: "M" },
  { id: "s7", productId: "p4", productName: "Pantalón Casual Club", brand: "Casual Club", quantity: 25, unitPrice: 22000, cost: 10000, date: "2026-01-25", size: "L" },
  { id: "s8", productId: "p4", productName: "Pantalón Casual Club", brand: "Casual Club", quantity: 20, unitPrice: 22000, cost: 10000, date: "2026-03-20", size: "M" },
  { id: "s9", productId: "p1", productName: "Remera Urban Fit", brand: "Urban Fit", quantity: 45, unitPrice: 25000, cost: 12000, date: "2026-03-25", size: "S" },
  { id: "s10", productId: "p6", productName: "Zapatillas SportPlus", brand: "SportPlus", quantity: 10, unitPrice: 55000, cost: 25000, date: "2026-02-05", size: "L" },
  { id: "s11", productId: "p7", productName: "Sweater EcoWear", brand: "EcoWear", quantity: 12, unitPrice: 35000, cost: 16000, date: "2026-04-01", size: "M" },
  { id: "s12", productId: "p8", productName: "Jean Recto 315", brand: "Casual Club", quantity: 60, unitPrice: 45000, cost: 20000, date: "2026-04-10", size: "XS" },
]

export const HOLIDAYS = [
  { date: "2026-01-01", name: "Año Nuevo" },
  { date: "2026-02-16", name: "Carnaval" },
  { date: "2026-03-24", name: "Día de la Memoria" },
  { date: "2026-05-01", name: "Día del Trabajador" },
  { date: "2026-05-25", name: "Revolución de Mayo" },
]
