services:
  - type: web
    name: tienda-de-ropa
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyDpaNWYpfAI45bMQKoOHzIGKWvESKVIx50
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: tienda-de-ropa-35bea.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: tienda-de-ropa-35bea
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: tienda-de-ropa-35bea.firebasestorage.app
      - key: VITE_FIREBASE_SENDER_ID
        value: "961273079910"
      - key: VITE_FIREBASE_APP_ID
        value: 1:961273079910:web:0c82c93ab5895b8ad725a7
      - key: VITE_FIREBASE_MEASUREMENT_ID
        value: G-7KMX0D6WVW
